### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by jonthus** [bgran/pycrypto#1]
Koodin dokumentaatio
Dokumentaatiota itsessään en kommentoi sen enempää (en löytänyt projektista dokumentaatiota muuta kuin viikkoraportit), mutta esimerkiksi jonkintyyppinen käyttöohje koodille voisi olla hyvä, ja enemmän kommentteja funktioissa itsessään niiden, jotka hieman avaisivat niiden toiminnasta. Tämän voi helposti totetuttaa esimerkiksi Docstringin avulla. Joissain luokissa näyttää olevan docstringimäinen kuvaus, mutta myös yksittäisten funktioiden toiminnan selitys voi auttaa myös koodin kirjoittamisessakin, sillä se auttaa kokonaiskuvan hahmottamista.

Koodin rakenne
Muutamassa tiedostossa on pitkä pätkä koodia laitettu (gen_rsa.py, decrypt.py, encrypt.py) main() -funktioon. Nämä voisi muuttaa siten, että osa koodista refaktoroitaisiin pois main-funktiosta yleisten koodikäytänteiden mukaisesti.
Muuten projektin rakenne yleisesti on kyllä hyvä, jokaisen tiedoston ja funktion toiminta yleisellä tasolla on helposti nähtävissä, ja se, miten ne liittyvät toisiinsa.

Koodin toiminta
Key-tiedoston generointi onnistuu hyvin. Koodi luo onnistuneesti tiedoston, jossa on alkuluvut generoituna. 
Rsa.py tiedostoa en saanut toimimaan, tulee error "Prime object has no attribute "print_stop"".
Encrypt ja decrypt tiedostoissa tulikin ilmoitus, että ei ole vielä mahdollista kokeilla manuaalisesti.

Testaaminen
Suosittelen test_prime funktiossa testaamaan jo tiedetyllä alkuluvulla, joko pienellä tai suurella, että toimiiko avainten generointi oikeasti oikein. Tällä hetkellä periaatteessa testi testaa vain sitä, että onnistuuko ohjelman ajaminen. Muut testit näyttävät olevan ihan toimivia.

Työsi näyttää kuitenkin jo edistyneen todella pitkälle, hyvää työtä!

**Comment by bgran** [comment]
Kiitos arvioinnista.

Esität hyviä pointteja, joista otan varmasti neuvoja.
