### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by ItsTuukka** [bgran/pycrypto#2]
Koodi ladattu, testattu ja arvioitu 9.12.2021 klo: 21.30

### Asennus ja komentorivikomennot

Projekti ladattu koneelle, mutta mitään "ohjelmaa" ei ole ajettavaksi. Koodia on siis katselmoitu ja yritetty ajaa tiedostoissaan, mutta käytännöllisyyttä ei ole päästy testaamaan. Testeille tarkoitettu `make tests` komento ei toimi import errorin takia. (Itselläkin ollut ongelmia pythonin import ominaisuuden kanssa, joskus saanut ratkaistua antamalla luokan moduulista parametriksi). 

### Dokumentaatio ja koodin kommentointi

Määrittelydokumentista uupuu muutama kurssilla vaadittava asia, kuten aikavaativuudet ja lähteet. Dokumentaatio testaus- ja toteutusdokumentin osalta vielä aika kesken. Coveragea varten suosittelen kuvaa tekstin sijasta. Hieman myös hämmentää kun read.md ja koodin kommentointi on englanniksi, mutta muuten suomeksi. Koodin kommentointi hyvin vajanaista, mikä vaikeuttaa koodin lukemista.

### Koodi ja sen rakenne

Koodin rakenne on vähän "all over the place", selkeät alahkemistot ja pitkien tiedostojen pilkkominen pienempiin palasiin auttaisi suunnattomasti (monta luokkaa yhdessä tiedostossa jne). Tämä tekisi myös git repost paljon siistimmän näköisen ja helpompi lukuisen. Koodin toimivuudesta vaikea kommentoida, koska selkeää ajettavaa osaa ei ole, ja melkein jokaisen tiedoston yksin ajamisessa tulee import tai joku muu error. Paljon on kyllä tavaraa, joten refaktorointi ja homma saattaa hyvinkin olla hienolla mallilla!
Vinkki pienten alkulukujen etsimisen optimointiin ([ks. Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)).

### Testaus

Testejä on vielä hyvin vähän ja niitäkään en pystynyt ajamaan yllä mainitsemani import errorin takia.

Hyvää duunia ja onnea jatkoon!

**Comment by bgran** [comment]
Kiitos arviosta. Tuossa on hyviä pointteja sinulta. Refaktorointi saataa olla aiheellista. Tiedän Eratostheneen seulasta mutta en vielä toteuttanut sitä.
